@startuml(id=wst.common)

hide stereotype
skinparam handwritten false
skinparam componentStyle rectangle

!define contributes "contributes to"

<style>
document {
  fontName Gadugi
  fontSize 14
  fontStyle normal

  title {
    fontSize 16
    fontStyle bold
    FontColor #666666
  }
}

componentDiagram {
  arrow {
    LineColor #888888
    LineThickness 2
    FontSize 10
    FontColor #666666
  }
}  

component {
  backgroundColor #f9f9f9
  LineColor #888888
  roundCorner 10
  LineThickness 2
  FontColor #666666

  .FL3 {
    backgroundColor #e8d0de
    LineColor #d3a5c1
  }

  .FL2 {
    backgroundColor #d5e2f3
    LineColor #a8c4ec
  }

  .FL1 {
    backgroundColor #d4e7d4
    LineColor #99c8be
  }
}

package {
  backgroundColor #GhostWhite
  lineColor #cccccc
  lineStyle 4-4

  FontName Gadugi
  FontSize 14
  FontStyle normal
  FontColor #666666
}

</style>

@enduml

@startuml(id=wst.legend)

<style>
legend {
  backgroundColor #GhostWhite
  LineColor #GhostWhite
  entrySeparator #GhostWhite
  
  fontName Gadugi
  fontSize 14
  FontColor #666666
}
</style>

legend bottom left
  <#GhostWhite,#GhostWhite>|        |= Legend |
  |<#e8d0de> | Flight Level 3|
  |<#d5e2f3> | Flight Level 2|
  |<#d4e7d4> | Flight Level 1|
endlegend
@enduml

@startuml(id=wsd.branding)
right footer Thomas Krause - worksystems.design
@enduml
