@startuml(id=wst.common)

hide stereotype
skinparam handwritten false
skinparam arrowColor #888888
skinparam arrowThickness 2
skinparam arrowFontSize 10
skinparam componentStyle rectangle

skinparam fontName Gadugi
skinparam fontSize 14
skinparam fontStyle normal

skinparam componentFontColor #666666
skinparam cardFontColor #666666
skinparam arrowFontColor #666666
skinparam legendFontColor #666666
skinparam packageFontColor #666666

skinparam sameComponentWidth<<FL2>> true

!define contributes "contributes to"

skinparam component {
  backgroundColor #f9f9f9
  borderColor #888888
  roundCorner 10
  borderThickness 2
}

skinparam component<<FL3>> {
  backgroundColor #e8d0de
  borderColor #d3a5c1
}

skinparam component<<FL2>> {
  backgroundColor #d5e2f3
  borderColor #a8c4ec
}

skinparam component<<FL1>> {
  backgroundColor #d4e7d4
  borderColor #99c8be
}

skinparam card {
  BackgroundColor<<FL2>> #d5e2f3
  BorderColor<<FL2>> #a8c4ec

  roundCorner 10
  borderThickness 2

  fontName Gadugi
  fontSize 14
  fontStyle normal
}

skinparam package {
  backgroundColor #GhostWhite
  borderColor #cccccc
  borderStyle dashed

  fontName Gadugi
  fontSize 14
  fontStyle normal
}
@enduml

@startuml(id=wst.legend)
skinparam legend {
  backgroundColor #GhostWhite
  borderColor #GhostWhite
  entrySeparator #GhostWhite
  fontName Gadugi
  fontSize 14
}

legend bottom left
  <#GhostWhite,#GhostWhite>|        |= Legend |
  |<#e8d0de> | Flight Level 3|
  |<#d5e2f3> | Flight Level 2|
  |<#d4e7d4> | Flight Level 1|
endlegend
@enduml

@startuml(id=wsd.branding)
right footer Thomas Krause - worksystems.design
@enduml
