@startuml

!include defs/fl-wst.iuml

package NoLevel {
    [No level]
}

package FL3 <<FL3>> {
  [Strategy] <<FL3>>
}

package FL2 <<FL2>> {
  [Tactic] <<FL2>>
}

package FL1 <<FL1>> {
  [Operation] <<FL1>>
}

@enduml