@startuml

!include defs/fl-wst.iuml

package NoLevel {
    [No level]
}

package FL3 <<FL3>> {
  [Strategy] worksystem(3)
}

package FL2 <<FL2>> {
  [Tactic] worksystem(2)
}

package FL1 <<FL1>> {
  [Operation] worksystem(1)
}

@enduml